### ISSUE TITLE
python3.6.9

### ISSUE THREAD

**Issue by Manarit** [adafruit/Adafruit_CircuitPython_ServoKit#46]
usr/bin/python3 /home/nano/Desktop/PyProjects/teste_servos.py
Traceback (most recent call last):
  File "/home/nano/Desktop/PyProjects/teste_servos.py", line 1, in <module>
    from adafruit_servokit import ServoKit
  File "/usr/local/lib/python3.6/dist-packages/adafruit_servokit.py", line 35, in <module>
    import board
  File "/usr/local/lib/python3.6/dist-packages/board.py", line 39, in <module>
    import adafruit_platformdetect.constants.boards as ap_board
  File "/usr/local/lib/python3.6/dist-packages/adafruit_platformdetect/__init__.py", line 10, in <module>
    from .board import Board
  File "/usr/local/lib/python3.6/dist-packages/adafruit_platformdetect/board.py", line 24
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined

I've already tryed to upgrade to 3.8 for example, but i have others issues, like just install opencv on the 3.6. or pip continue using the previous one.

How can i update my jetson? I'm using one by "yahboom" store.

I'm a beginner user.

**Comment by tekktrik** [comment]
The base for Blinka is now Python 3.7, you can find instructions on how to update [in this Learn Guide](https://learn.adafruit.com/circuitpython-libraries-on-linux-and-the-nvidia-jetson-nano/initial-setup).
